from chessBoard import chessBoard

chessboard = chessBoard()
chessboard.Get_Chess_Piece_Locations()
chessboardMap = chessboard.get_Chessboard()
#print()
#chessboard.Get_Chess_Piece_Truth_Locations()
#chessboard.Get_Board_Spot_Numers_And_Cords()
#print()
#chessboard.Get_Board_FEN_Map()
#print()
#chessboard.Print_Each_Teams_Alive_Pieces()
print()
#chessboard.white_Team.get_All_Possible_Moves_For_All_Alive_Pieces(chessboardMap)
print()
#chessboard.black_Team.get_All_Possible_Moves_For_All_Alive_Pieces(chessboardMap)
#print()
chessboard.white_Team.check_King_Is_Checked_Or_Checkmated(chessboardMap, chessboard.black_Team)
print()
#print(chessboardMap[7][7].get_Chess_Piece().name)
#print(chessboardMap[7][7].getCords())
#chessboardMap[1][1].get_Chess_Piece().getMovableSpaces(chessboardMap)
